app:
  # application environment. (local, dev, test, prod)
  env: "local"
  port: "9082"
  version: "1.0.12"

broker:
  # kafka_protocol://kafka_username:kafka_password@kafka_host:kafka_port/kafka_partition
  url: "kafka://:@localhost:9092/0"
  # app name for kafka consumer group
  consumer_group: "bb.app.dev.certificateservice"
  # topic for kafka consumer
  topic: "bb.topic.dev.certification"
  # topic for kafka producer (reader related dead letter topic)
  topic_dead_letter: "bb.topic.dev.dl.certification"

cdn:
  # cdn endpoint
  endpoint: "http://localhost:9000"
  region: "tr-1"
  bucket: "certification"
  access_key: "minio"
  secret_key: "minio123"
